export const TopwareProducts = [
  {
    ProductName: "Shiro Hoodie",
    ProductPrice: "3,499.00",
    href: "/tshirts/kageHoodie",
    src: "/hoodie1.jpg",
    price: 3499,
  },
  {
    ProductName: "Wake Hoodie",
    ProductPrice: "2,999.00",
    href: "/tshirts/wakeHoodie",
    src: "/hoodie2.jpg",
    price: 2999,
  },
  {
    ProductName: "Aka Hoodie",
    ProductPrice: "4,999",
    href: "/tshirts/whiteHoodie",
    src: "/hoodie3.jpg",
    price: 4999,
  },
  {
    ProductName: "Kage Jacket",
    ProductPrice: "6,499.00",
    href: "/tshirts/kageJacket",
    src: "/jacket1.jpg",
    price: 6499,
  },
  {
    ProductName: "Basic Hoodie",
    ProductPrice: "2,499.00",
    href: "/tshirts/whiteHoodie",
    src: "/jacket2.jpg",
    price: 2499,
  },
  {
    ProductName: "Kage Jacket",
    ProductPrice: "6,499.00",
    href: "/tshirts/kageJacket",
    src: "/jacket1.jpg",
    price: 6499,
  },
  {
    ProductName: "Wake Hoodie",
    ProductPrice: "2,999.00",
    href: "/tshirts/wakeHoodie",
    src: "/hoodie2.jpg",
    price: 2999,
  },
  {
    ProductName: "Aka Hoodie",
    ProductPrice: "4,999.00",
    href: "/tshirts/whiteHoodie",
    src: "/hoodie3.jpg",
    price: 4999,
  },
  {
    ProductName: "Aka Hoodie",
    ProductPrice: "4,999.00",
    href: "/tshirts/whiteHoodie",
    src: "/hoodie3.jpg",
    price: 4999,
  },
  {
    ProductName: "Shiro Hoodie",
    ProductPrice: "3,499.00",
    href: "/tshirts/kageHoodie",
    src: "/hoodie1.jpg",
    price: 3499,
  },
  {
    ProductName: "Basic Hoodie",
    ProductPrice: "2,499.00",
    href: "/tshirts/whiteHoodie",
    src: "/jacket2.jpg",
    price: 2499,
  },
  {
    ProductName: "Kage Jacket",
    ProductPrice: "6,499.00",
    href: "/tshirts/kageJacket",
    src: "/jacket1.jpg",
    price: 6499,
  },
];

export const TopwareProductsForHomePage = [
  {
    ProductName: "Shiro Hoodie",
    ProductPrice: "3,499.00",
    href: "/tshirts/kageHoodie",
    src: "/hoodie1.jpg",
    price: 3499,
  },
  {
    ProductName: "Wake Hoodie",
    ProductPrice: "2,999.00",
    href: "/tshirts/wakeHoodie",
    src: "/hoodie2.jpg",
    price: 2999,
  },
  {
    ProductName: "Aka Hoodie",
    ProductPrice: "4,999",
    href: "/tshirts/whiteHoodie",
    src: "/hoodie3.jpg",
    price: 4999,
  },
  {
    ProductName: "Kage Jacket",
    ProductPrice: "6,499.00",
    href: "/tshirts/kageJacket",
    src: "/jacket1.jpg",
    price: 6499,
  },
];
